import { Token, DRTToken, UserProfile, TransactionContext, Scenario, Rule } from './types';

export const sampleTokens: Token[] = [
  {
    id: 'token_chase_sapphire',
    name: 'Chase Sapphire Preferred',
    dpan: '**** **** **** 4521',
    type: 'credit',
    network: 'visa',
    limit: 10000,
    balance: 2500,
    utilization: 0.25,
    apr: 21.99,
    ftf: 0,
    blockedMCCs: [],
    rewardsByCategory: { dining: 3, travel: 2, streaming: 2, default: 1 },
    isEligible: true,
    cashbackRate: 0,
    signupBonus: { threshold: 4000, current: 2800, reward: 60000 },
  },
  {
    id: 'token_amex_gold',
    name: 'Amex Gold',
    dpan: '**** **** **** 3782',
    type: 'credit',
    network: 'amex',
    limit: 15000,
    balance: 4500,
    utilization: 0.30,
    apr: 19.99,
    ftf: 0,
    blockedMCCs: [5542, 5541],
    rewardsByCategory: { dining: 4, groceries: 4, travel: 3, default: 1 },
    isEligible: true,
    cashbackRate: 0,
  },
  {
    id: 'token_citi_double',
    name: 'Citi Double Cash',
    dpan: '**** **** **** 8834',
    type: 'credit',
    network: 'mastercard',
    limit: 8000,
    balance: 1200,
    utilization: 0.15,
    apr: 18.99,
    ftf: 3,
    blockedMCCs: [],
    rewardsByCategory: { default: 2 },
    isEligible: true,
    cashbackRate: 2,
  },
  {
    id: 'token_discover_it',
    name: 'Discover It',
    dpan: '**** **** **** 6011',
    type: 'credit',
    network: 'discover',
    limit: 5000,
    balance: 800,
    utilization: 0.16,
    apr: 22.99,
    ftf: 0,
    blockedMCCs: [],
    rewardsByCategory: { dining: 5, groceries: 5, gas: 5, default: 1 },
    isEligible: true,
    cashbackRate: 1,
  },
  {
    id: 'token_debit_checking',
    name: 'Chase Debit',
    dpan: '**** **** **** 9912',
    type: 'debit',
    network: 'visa',
    limit: 0,
    balance: 3500,
    utilization: 0,
    apr: 0,
    ftf: 3,
    blockedMCCs: [],
    rewardsByCategory: { default: 0 },
    isEligible: true,
    cashbackRate: 0,
  },
];

export const sampleDRTToken: DRTToken = {
  id: 'drt_premium_wallet',
  name: 'Premium Wallet DRT',
  dpan: '**** **** **** 0001',
  type: 'drt',
  network: 'visa',
  limit: 0,
  balance: 0,
  utilization: 0,
  apr: 0,
  ftf: 0,
  blockedMCCs: [],
  rewardsByCategory: {},
  isEligible: true,
  cashbackRate: 0,
  routingStrategy: 'optimal_score',
  childDPANs: [
    {
      id: 'child_venture_x',
      name: 'Capital One Venture X',
      dpan: '**** **** **** 7744',
      type: 'credit',
      network: 'visa',
      limit: 20000,
      balance: 3000,
      utilization: 0.15,
      apr: 20.99,
      ftf: 0,
      blockedMCCs: [],
      rewardsByCategory: { travel: 10, dining: 2, default: 2 },
      isEligible: true,
      cashbackRate: 0,
    },
    {
      id: 'child_freedom_flex',
      name: 'Chase Freedom Flex',
      dpan: '**** **** **** 5566',
      type: 'credit',
      network: 'visa',
      limit: 6000,
      balance: 900,
      utilization: 0.15,
      apr: 19.99,
      ftf: 3,
      blockedMCCs: [],
      rewardsByCategory: { dining: 3, drugstores: 3, default: 1 },
      isEligible: true,
      cashbackRate: 0,
    },
    {
      id: 'child_blue_cash',
      name: 'Amex Blue Cash Preferred',
      dpan: '**** **** **** 2233',
      type: 'credit',
      network: 'amex',
      limit: 12000,
      balance: 2400,
      utilization: 0.20,
      apr: 17.99,
      ftf: 2.7,
      blockedMCCs: [],
      rewardsByCategory: { groceries: 6, streaming: 6, gas: 3, default: 1 },
      isEligible: true,
      cashbackRate: 0,
    },
  ],
};

export const sampleUser: UserProfile = {
  id: 'user_demo_001',
  name: 'Demo User',
  tokens: sampleTokens,
  drtTokens: [sampleDRTToken],
  cashBalance: 3500,
  daysToPaycheck: 12,
  preferenceWeights: { rewards: 0.40, credit: 0.25, cashflow: 0.20, risk: 0.15 },
  riskTolerance: 'medium',
  defaultToken: 'token_chase_sapphire',
};

export const sampleRules: Rule[] = [
  {
    id: 'rule_dining_premium',
    label: 'Force Amex Gold for Dining',
    type: 'HARD',
    priority: 1,
    enabled: true,
    condition: { field: 'mcc', operator: 'in', value: [5812, 5814, 5813] },
    action: { type: 'FORCE', targetTokenId: 'token_amex_gold', reason: 'Amex Gold has 4x on dining (hard override)' },
    compiledDSL: 'IF mcc IN [5812, 5814, 5813] THEN FORCE token_amex_gold',
  },
  {
    id: 'rule_foreign_exclude_ftf',
    label: 'Exclude FTF Cards Abroad',
    type: 'HARD',
    priority: 2,
    enabled: true,
    condition: { field: 'country', operator: 'neq', value: 'US' },
    action: { type: 'EXCLUDE', targetTokenProperty: 'ftf', targetPropertyValue: { gt: 0 }, reason: 'Foreign transaction fee applies' },
    compiledDSL: 'IF country != "US" THEN EXCLUDE tokens WHERE ftf > 0',
  },
  {
    id: 'rule_high_util_exclude',
    label: 'Exclude High Utilization (>30%)',
    type: 'SOFT',
    priority: 3,
    enabled: true,
    condition: { field: 'projected_utilization', operator: 'gt', value: 0.30 },
    action: { type: 'EXCLUDE', reason: 'Projected utilization exceeds 30% threshold' },
    compiledDSL: 'IF projected_utilization > 0.30 THEN EXCLUDE token',
  },
  {
    id: 'rule_signup_bonus_boost',
    label: 'Boost Signup Bonus Progress',
    type: 'SOFT',
    priority: 4,
    enabled: true,
    condition: { field: 'has_active_signup_bonus', operator: 'eq', value: true },
    action: { type: 'BOOST', boostAmount: 15, reason: 'Active signup bonus in progress (+15 normalized)' },
    compiledDSL: 'IF has_active_signup_bonus = true THEN BOOST +15',
  },
  {
    id: 'rule_discover_acceptance',
    label: 'Penalize Low-Acceptance Networks',
    type: 'SOFT',
    priority: 5,
    enabled: true,
    condition: { field: 'network_acceptance_risk', operator: 'eq', value: 'high' },
    action: { type: 'PENALIZE', penaltyAmount: 10, reason: 'Network acceptance risk penalty (-10)' },
    compiledDSL: 'IF network_acceptance_risk = "high" THEN PENALIZE -10',
  },
  {
    id: 'rule_gas_station_block',
    label: 'Exclude Amex at Gas Stations',
    type: 'HARD',
    priority: 6,
    enabled: true,
    condition: { field: 'mcc', operator: 'in', value: [5541, 5542] },
    action: { type: 'EXCLUDE', targetTokenProperty: 'network', targetPropertyValue: 'amex', reason: 'Amex blocked at gas pumps' },
    compiledDSL: 'IF mcc IN [5541, 5542] THEN EXCLUDE WHERE network = "amex"',
  },
  {
    id: 'rule_travel_boost',
    label: 'Boost Travel Cards for Travel',
    type: 'SOFT',
    priority: 7,
    enabled: true,
    condition: { field: 'category', operator: 'eq', value: 'travel' },
    action: { type: 'BOOST', boostAmount: 8, targetTokenProperty: 'rewardsByCategory.travel', targetPropertyValue: { gt: 2 }, reason: 'Travel category bonus (+8)' },
    compiledDSL: 'IF category = "travel" THEN BOOST tokens WHERE travel > 2 BY +8',
  },
  {
    id: 'rule_low_balance_debit',
    label: 'Penalize Low Debit Balance',
    type: 'SOFT',
    priority: 8,
    enabled: true,
    condition: { field: 'debit_balance_low', operator: 'eq', value: true },
    action: { type: 'PENALIZE', penaltyAmount: 20, reason: 'Insufficient debit buffer (-20)' },
    compiledDSL: 'IF debit_balance < amount × 2 THEN PENALIZE -20',
  },
];

export const scenarios: Scenario[] = [
  {
    id: 'scenario_dining_domestic',
    name: '🍽️ Domestic Dining',
    description: 'Restaurant purchase in the US',
    expectedOutcome: 'HARD RULE forces Amex Gold (4x dining). Optimizer would pick Discover It (5x) but rule overrides.',
    context: { amount: 85.50, currency: 'USD', merchant: 'The Capital Grille', mcc: 5812, category: 'dining', country: 'US', walletType: 'apple_pay', isInPerson: true, riskFlags: [] },
  },
  {
    id: 'scenario_intl_travel',
    name: '✈️ International Travel',
    description: 'Hotel booking abroad (France)',
    expectedOutcome: 'Excludes Citi Double Cash (3% FTF) and Debit (3% FTF). Selects best no-FTF card by score.',
    context: { amount: 450.00, currency: 'EUR', merchant: 'Hotel & Spa Paris', mcc: 7011, category: 'travel', country: 'FR', walletType: 'browser', isInPerson: false, riskFlags: [] },
  },
  {
    id: 'scenario_gas_station',
    name: '⛽ Gas Station',
    description: 'Gas pump purchase',
    expectedOutcome: 'HARD RULE excludes all Amex cards (blocked MCC). Selects Discover It (5x gas) or Citi.',
    context: { amount: 62.30, currency: 'USD', merchant: 'Shell Gas Station', mcc: 5541, category: 'gas', country: 'US', walletType: 'google_pay', isInPerson: true, riskFlags: [] },
  },
  {
    id: 'scenario_grocery',
    name: '🛒 Grocery Shopping',
    description: 'Weekly grocery run at Whole Foods',
    expectedOutcome: 'No hard override. Optimizer selects Amex Gold (4x groceries) or Discover It (5x groceries).',
    context: { amount: 156.78, currency: 'USD', merchant: 'Whole Foods Market', mcc: 5411, category: 'groceries', country: 'US', walletType: 'apple_pay', isInPerson: true, riskFlags: [] },
  },
  {
    id: 'scenario_high_risk',
    name: '⚠️ High Risk Online',
    description: 'Large online purchase with multiple risk flags',
    expectedOutcome: 'Risk score elevated (>0.5). May veto selection or increase decline probability significantly.',
    context: { amount: 2500.00, currency: 'USD', merchant: 'Electronics Warehouse', mcc: 5732, category: 'electronics', country: 'US', walletType: 'browser', isInPerson: false, riskFlags: ['high_amount', 'new_merchant', 'velocity_spike'] },
  },
  {
    id: 'scenario_signup_bonus',
    name: '🎯 Signup Bonus Chase',
    description: 'Purchase to hit Chase Sapphire bonus',
    expectedOutcome: 'Signup bonus rule boosts Chase Sapphire (+15). May win over cards with higher base rewards.',
    context: { amount: 350.00, currency: 'USD', merchant: 'Best Buy', mcc: 5732, category: 'electronics', country: 'US', walletType: 'samsung_pay', isInPerson: true, riskFlags: [] },
  },
  {
    id: 'scenario_streaming',
    name: '📺 Streaming Service',
    description: 'Monthly streaming subscription renewal',
    expectedOutcome: 'Optimizer picks card with best streaming rewards. Chase Sapphire (2x) or Blue Cash Preferred (6x).',
    context: { amount: 15.99, currency: 'USD', merchant: 'Netflix', mcc: 4899, category: 'streaming', country: 'US', walletType: 'browser', isInPerson: false, riskFlags: [] },
  },
  {
    id: 'scenario_large_purchase',
    name: '💎 Large Purchase',
    description: 'High-value electronics purchase testing utilization limits',
    expectedOutcome: 'May exclude cards that would exceed 30% utilization threshold. Tests credit health scoring.',
    context: { amount: 1899.00, currency: 'USD', merchant: 'Apple Store', mcc: 5732, category: 'electronics', country: 'US', walletType: 'apple_pay', isInPerson: true, riskFlags: ['high_amount'] },
  },
  {
    id: 'scenario_drt_test',
    name: '🔀 DRT Selection',
    description: 'Tests Dynamic Routing Token child selection',
    expectedOutcome: 'DRT resolves to best child card based on routing strategy (optimal_score picks highest scoring child).',
    context: { amount: 275.00, currency: 'USD', merchant: 'Marriott Hotels', mcc: 7011, category: 'travel', country: 'US', walletType: 'browser', isInPerson: false, riskFlags: [] },
  },
];

export function getDefaultContext(): TransactionContext {
  return {
    amount: 50.00,
    currency: 'USD',
    merchant: 'Generic Merchant',
    mcc: 5999,
    category: 'other',
    country: 'US',
    walletType: 'apple_pay',
    isInPerson: true,
    riskFlags: [],
    timestamp: Date.now(),
    correlationId: '',
  };
}

export const MCC_CATEGORIES: Record<number, string> = {
  5812: 'dining', 5813: 'dining', 5814: 'dining',
  5411: 'groceries', 5541: 'gas', 5542: 'gas',
  7011: 'travel', 4511: 'travel', 5732: 'electronics',
  5311: 'retail', 5999: 'other',
};

export const COUNTRIES = [
  { code: 'US', name: 'United States' },
  { code: 'CA', name: 'Canada' },
  { code: 'GB', name: 'United Kingdom' },
  { code: 'FR', name: 'France' },
  { code: 'DE', name: 'Germany' },
  { code: 'JP', name: 'Japan' },
  { code: 'MX', name: 'Mexico' },
];

export const WALLET_TYPES = [
  { value: 'apple_pay', label: 'Apple Pay' },
  { value: 'google_pay', label: 'Google Pay' },
  { value: 'samsung_pay', label: 'Samsung Pay' },
  { value: 'browser', label: 'Browser/Online' },
];

export const RISK_FLAGS = [
  'high_amount', 'new_merchant', 'velocity_spike',
  'geo_anomaly', 'time_anomaly', 'device_change', 'card_not_present',
];
